name: Build NDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Set up NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip android-ndk-r25b-linux.zip -d $HOME
        echo "$HOME/android-ndk-r25b" >> $GITHUB_PATH

    - name: Build NDK
      run: |
        cd OpenSock_3.3.0
        ndk-build -C jni

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ndk-build-output
        path: OpenSock_3.3.0/jni/libs
